default: &default
  adapter: postgresql
  pool: 5
  username: postgres

development:
  <<: *default
  database: phadder_development

test: &test
  <<: *default
  database: phadder_test

production:
  <<: *default
  database: phadder_production
